\newpage
# Excercise Checklist

This checklist should help you keeping track of your exercises. Remember that you have to hand in satisfactory solutions to at least two-thirds of the assignments. If you're part of the beginner track, this refers to two-thirds of part A (EDA) only. If you're part of the advanced track, you have to hand in at least two-thirds of both individual parts A and B. Hence, you cannot hand in 100 percent of the first and only 50 percent of the second one. You'll need more than 66% in each one for a certificate. After all, you're not that advanced if you only did half of it, right? :)

**Part A: Exploratory Data Analysis (Beginners + Advanced)**

**Data: Kaggle Data**

1. **Getting Started** 

1.1 Read in data, show data, and summarize data (mean, count, ...)

1.2 Compute column `duration_minutes` from `duration_ms`

1.3 Compute mean/std of `duration_minutes`. Which song has the longest duration?

1.4 Plot histogram of song durations


2. **Time Series: How did songs change over the years?**

2.1 Streaming leads to shorter songs? Group-By: song duration over years

2.2 Merge songs with song_features on id

2.3 Compare how features like `acousticness`, `danceability`, `energy`, `valence`, `speechiness`, and `instrumentalness` changed over time

2.4 For Advanced: Radar plot (aka spider plot or polar plot) over time

3. **Artists**

3.1 Bar plot with artists with most songs

3.2 For Advanced: Map with top songs in each country

4. **Pairplot: Artist Comparison**

4.1 Look for three different artists and compare the features of the songs with a pairplot

4.2 Look at the proposed gallery and look for a plot that you could use to visualize an aspect of the Spotify data and generate a plot

4.3 What is the message of your plot? What does it show?


**Data: Personal Spotify Data**

5. **Personal Data**

5.1 Generate a bar plot with top 10 artists

5.2 Visualize when you listened to music. On which days, at which times?


**Part B: Popularity Prediction Using Statistical Methods ((motivated) Beginners + Advanced)**


**Data: Kaggle Data**

1. Create a correlation plot between features

2. Regression 

2.1 Create a simple linear model to predict the popularity of a song

2.2 Improve your model using more features

3. Train/test your model 

4. Develop more advanced models
